config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :conditions do
  member do
    get "vote"
  end
end

  resources :accounts

  resources :deliveries

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/condition.rb
class Condition < ActiveRecord::Base
  belongs_to :user
  has_many :deliveries
  has_many :accounts
  acts_as_votable 
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_condition, only: [:show, :edit, :update, :destroy, :vote]

  # GET /conditions
  # GET /conditions.json
  def index
    @conditions = Condition.all
  end

  # GET /conditions/1
  # GET /conditions/1.json
  def show
  end

  # GET /conditions/new
  def new
    @condition = Condition.new
  end

  # GET /conditions/1/edit
  def edit
  end

  # POST /conditions
  # POST /conditions.json
  def create
    @condition = Condition.new(condition_params)
    @condition.user = current_user

    respond_to do |format|
      if @condition.save
        format.html { redirect_to @condition, notice: 'Condition was successfully created.' }
        format.json { render :show, status: :created, location: @condition }
      else
        format.html { render :new }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conditions/1
  # PATCH/PUT /conditions/1.json
  def update
    respond_to do |format|
      if @condition.update(condition_params)
        format.html { redirect_to @condition, notice: 'Condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @condition }
      else
        format.html { render :edit }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conditions/1
  # DELETE /conditions/1.json
  def destroy
    @condition.destroy
    respond_to do |format|
      format.html { redirect_to conditions_url, notice: 'Condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @condition.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition
      @condition = Condition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condition_params
      params.require(:condition).permit(:name, :item, :key, :order_count, :cur_count, :user_id)
    end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/_form.html.erb
<%= form_for @condition, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :item, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :item, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :key, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :key, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_count, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :order_count, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cur_count, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :cur_count, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  conditions_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/conditions/edit.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Condition %></h1>
</div>
<%= render :partial => 'form' %>

app/views/conditions/index.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => Condition %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:item) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%= model_class.human_attribute_name(:order_count) %></th>
      <th><%= model_class.human_attribute_name(:cur_count) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @conditions.each do |condition| %>
      <tr>
        <td><%= condition.id %></td>
        <td><%= condition.name %></td>
        <td><%= condition.item %></td>
        <td><%= condition.key %></td>
        <td><%= condition.order_count %></td>
        <td><%= condition.cur_count %></td>
        <td><%=l condition.created_at, format: :long %></td>
        <td>
          <%= link_to condition_path(condition), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to condition_path(condition), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_condition_path,
            :class => 'btn btn-primary' %>

app/views/conditions/new.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Condition %></h1>
</div>
<%= render :partial => 'form' %>

app/views/conditions/show.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => Condition %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @condition.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:item) %></dt>
      <dd><pre class="prettyprint"><%= @condition.item %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:key) %></dt>
      <dd><pre class="prettyprint"><%= @condition.key %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:order_count) %></dt>
      <dd><pre class="prettyprint"><%= @condition.order_count %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cur_count) %></dt>
      <dd><pre class="prettyprint"><%= @condition.cur_count %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              conditions_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_condition_path(@condition), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              condition_path(@condition),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>