config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :conditions do
  member do
    get "vote"
  end
end

  resources :accounts

  resources :deliveries

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  belongs_to :user
  belongs_to :condition
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_delivery, only: [:show, :edit, :update, :destroy]

  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = Delivery.new(delivery_params)
    @delivery.user = current_user

    respond_to do |format|
      if @delivery.save
        format.html { redirect_to @delivery, notice: 'Delivery was successfully created.' }
        format.json { render :show, status: :created, location: @delivery }
      else
        format.html { render :new }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_params
      params.require(:delivery).permit(:first_name, :last_name, :address_line1, :address_line2, :zip_code, :city, :state, :country, :phone_number, :amazon_email, :amazon_password, :user_id, :condition_id)
    end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/_form.html.erb
<%= form_for @delivery, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :first_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :last_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_line1, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address_line1, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_line2, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address_line2, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip_code, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :zip_code, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :city, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :state, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :country, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amazon_email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :amazon_email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amazon_password, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :amazon_password, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  deliveries_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<%- model_class = Delivery -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Delivery %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deliveries/index.html.erb
<%- model_class = Delivery -%>
<div class="page-header">
  <h1><%=t '.title', :default => Delivery %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:address_line1) %></th>
      <th><%= model_class.human_attribute_name(:address_line2) %></th>
      <th><%= model_class.human_attribute_name(:zip_code) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%= model_class.human_attribute_name(:amazon_email) %></th>
      <th><%= model_class.human_attribute_name(:amazon_password) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.id %></td>
        <td><%= delivery.first_name %></td>
        <td><%= delivery.last_name %></td>
        <td><%= delivery.address_line1 %></td>
        <td><%= delivery.address_line2 %></td>
        <td><%= delivery.zip_code %></td>
        <td><%= delivery.city %></td>
        <td><%= delivery.state %></td>
        <td><%= delivery.country %></td>
        <td><%= delivery.phone_number %></td>
        <td><%= delivery.amazon_email %></td>
        <td><%= delivery.amazon_password %></td>
        <td><%=l delivery.created_at, format: :long %></td>
        <td>
          <%= link_to delivery_path(delivery), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to delivery_path(delivery), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_delivery_path,
            :class => 'btn btn-primary' %>

app/views/deliveries/new.html.erb
<%- model_class = Delivery -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Delivery %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deliveries/show.html.erb
<%- model_class = Delivery -%>
<div class="page-header">
  <h1><%=t '.title', :default => Delivery %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_name) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:last_name) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.last_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address_line1) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.address_line1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address_line2) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.address_line2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:zip_code) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.zip_code %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:city) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:state) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.state %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:country) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.country %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone_number) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.phone_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:amazon_email) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.amazon_email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:amazon_password) %></dt>
      <dd><pre class="prettyprint"><%= @delivery.amazon_password %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              deliveries_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_delivery_path(@delivery), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              delivery_path(@delivery),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>