config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :conditions do
  member do
    get "vote"
  end
end

  resources :accounts

  resources :deliveries

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  belongs_to :condition
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user = current_user

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name_on_card, :card_number, :security_code, :expiration_month, :expiration_year, :billing_first_name, :billing_last_name, :address_line1, :address_line2, :zip_code, :city, :state, :country, :phone_number, :user_id, :condition_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name_on_card, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name_on_card, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :card_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :card_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :security_code, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :security_code, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :expiration_month, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :expiration_month, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :expiration_year, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :expiration_year, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :billing_first_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :billing_first_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :billing_last_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :billing_last_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_line1, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address_line1, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_line2, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address_line2, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip_code, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :zip_code, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :city, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :state, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :country, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone_number, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Account %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => Account %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name_on_card) %></th>
      <th><%= model_class.human_attribute_name(:card_number) %></th>
      <th><%= model_class.human_attribute_name(:security_code) %></th>
      <th><%= model_class.human_attribute_name(:expiration_month) %></th>
      <th><%= model_class.human_attribute_name(:expiration_year) %></th>
      <th><%= model_class.human_attribute_name(:billing_first_name) %></th>
      <th><%= model_class.human_attribute_name(:billing_last_name) %></th>
      <th><%= model_class.human_attribute_name(:address_line1) %></th>
      <th><%= model_class.human_attribute_name(:address_line2) %></th>
      <th><%= model_class.human_attribute_name(:zip_code) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.name_on_card %></td>
        <td><%= account.card_number %></td>
        <td><%= account.security_code %></td>
        <td><%= account.expiration_month %></td>
        <td><%= account.expiration_year %></td>
        <td><%= account.billing_first_name %></td>
        <td><%= account.billing_last_name %></td>
        <td><%= account.address_line1 %></td>
        <td><%= account.address_line2 %></td>
        <td><%= account.zip_code %></td>
        <td><%= account.city %></td>
        <td><%= account.state %></td>
        <td><%= account.country %></td>
        <td><%= account.phone_number %></td>
        <td><%=l account.created_at, format: :long %></td>
        <td>
          <%= link_to account_path(account), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to account_path(account), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_account_path,
            :class => 'btn btn-primary' %>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Account %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => Account %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name_on_card) %></dt>
      <dd><pre class="prettyprint"><%= @account.name_on_card %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:card_number) %></dt>
      <dd><pre class="prettyprint"><%= @account.card_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:security_code) %></dt>
      <dd><pre class="prettyprint"><%= @account.security_code %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:expiration_month) %></dt>
      <dd><pre class="prettyprint"><%= @account.expiration_month %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:expiration_year) %></dt>
      <dd><pre class="prettyprint"><%= @account.expiration_year %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:billing_first_name) %></dt>
      <dd><pre class="prettyprint"><%= @account.billing_first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:billing_last_name) %></dt>
      <dd><pre class="prettyprint"><%= @account.billing_last_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address_line1) %></dt>
      <dd><pre class="prettyprint"><%= @account.address_line1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address_line2) %></dt>
      <dd><pre class="prettyprint"><%= @account.address_line2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:zip_code) %></dt>
      <dd><pre class="prettyprint"><%= @account.zip_code %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:city) %></dt>
      <dd><pre class="prettyprint"><%= @account.city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:state) %></dt>
      <dd><pre class="prettyprint"><%= @account.state %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:country) %></dt>
      <dd><pre class="prettyprint"><%= @account.country %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone_number) %></dt>
      <dd><pre class="prettyprint"><%= @account.phone_number %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>